integer=int(input("Enter an integer: "))
floatint=float(input("Enter a floating point integer: "))
complexnum=complex(input("Enter a complex number: "))

print(f"Integer: {integer}\nFloating point integer: {floatint}\nComplex number: {complexnum}")
print("Arithmetic Operations: ")
n1=int(input("Enter first number: "))
n2=int(input("Enter second number: "))
print("Addition: ",n1+n2)
print("Subtraction: ",n1-n2)
print("Multiplication: ",n1*n2)
print("Division: ",n1/n2)
print("Floor Division: ",n1//n2)
print("Modulus: ",n1%n2)
print("Exponentiation: ",n1**n2)
